### ISSUE TITLE
GET /.../available_items returns nothing useful

### ISSUE THREAD

**Issue by deiuch** [dds-project-f19/dds-backend#10]
__Expected:__ a list of available items for this user.

__Actual:__ `{ "items": null }`

**Comment by modbrin** [comment]
Check out new changes requested by @kzvdar42 [here](https://github.com/dds-project-f19/dds-backend/commit/638bfab77819b1df08e42e06517c429a977281b9#diff-04c6e90faac2675aa89e2176d2eec7d8R126)

**Comment by deiuch** [comment]
> Check out new changes requested by @kzvdar42 [here](https://github.com/dds-project-f19/dds-backend/commit/638bfab77819b1df08e42e06517c429a977281b9#diff-04c6e90faac2675aa89e2176d2eec7d8R126)

Got it! But it has no sence in terms of this issue :(

**Comment by deiuch** [comment]
The problem is that there's no difference in backend between `null` and `[]`. Resolved by handling on the frontend.
_Worth mentioning in `README.md`_
